//get
export const GET_CATEGORY_DETAILS_REQUEST = "GET_CATEGORY_DETAILS_REQUEST"
export const GET_CATEGORY_DETAILS_SUCCESS = "GET_CATEGORY_DETAILS_SUCCESS"
export const GET_CATEGORY_DETAILS_FAILED = "GET_CATEGORY_DETAILS_FAILED"


//post
export const POST_CATEGORY_DETAILS_REQUEST = "POST_CATEGORY_DETAILS_REQUEST"
export const POST_CATEGORY_DETAILS_SUCCESS = "POST_CATEGORY_DETAILS_SUCCESS"
export const POST_CATEGORY_DETAILS_FAILED = "POST_CATEGORY_DETAILS_FAILED"