//get

export const GET_EXPENSE_REQUEST = "GET_EXPENSE_REQUEST"
export const GET_EXPENSE_SUCCESS = "GET_EXPENSE_SUCCESS"
export const GET_EXPENSE_FAILED  = "GET_EXPENSE_FAILED"



//post

export const POST_EXPENSE_REQUEST = "POST_EXPENSE_REQUEST"
export const POST_EXPENSE_SUCCESS = "POST_EXPENSE_SUCCESS"
export const POST_EXPENSE_FAILED  = "POST_EXPENSE_FAILED"